# Generated by scripts/update-tap.sh in statico/ttmux. Edits here are overwritten
# by the next release.
class Ttmux < Formula
  desc "Modern multiplexer alternative with tiling and free-floating panes"
  homepage "https://github.com/statico/ttmux"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/statico/ttmux/releases/download/v0.3.0/ttmux-aarch64-apple-darwin.tar.gz"
      sha256 "34a22bbfd96e5a900bf7305537e1ac5e46e184b7e9595ba3c76fb8dd3b241674"
    end
    on_intel do
      url "https://github.com/statico/ttmux/releases/download/v0.3.0/ttmux-x86_64-apple-darwin.tar.gz"
      sha256 "b517d7a3d023bb64a3828bdf3c9f6ff8c46b8e86232ddffd62713c535ab59d6e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/statico/ttmux/releases/download/v0.3.0/ttmux-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0c47c5d16223348c026f11fe0d42e664961af275cd549377dad371d9a1f27a0c"
    end
    on_intel do
      url "https://github.com/statico/ttmux/releases/download/v0.3.0/ttmux-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "b8b7830e27f64fa2c7b89244837ea3d86747e04bcf9bc24afd19bf91f180a2b9"
    end
  end

  def install
    bin.install "ttmux"
  end

  test do
    assert_match "ttmux #{version}", shell_output("#{bin}/ttmux -V")
    # --where needs no terminal, so it works in the sandbox.
    assert_match "ttmux.toml", shell_output("#{bin}/ttmux --where")
  end
end
