# Generated by scripts/update-tap.sh in statico/ttmux. Edits here are overwritten
# by the next release.
class Ttmux < Formula
  desc "Modern multiplexer alternative with tiling and free-floating panes"
  homepage "https://github.com/statico/ttmux"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/statico/ttmux/releases/download/v0.4.0/ttmux-aarch64-apple-darwin.tar.gz"
      sha256 "2f4d89c665553e6300fc5d7d768224e45b258762f786c1bfa9bd577abb9fad33"
    end
    on_intel do
      url "https://github.com/statico/ttmux/releases/download/v0.4.0/ttmux-x86_64-apple-darwin.tar.gz"
      sha256 "c1ea6636977a280ac349bc7e572cb714cd3465ddc2fcfdf5f55ffd9d5b5e5021"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/statico/ttmux/releases/download/v0.4.0/ttmux-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "343822040e494b5f6fdc892d53f1ac58268c0a185ac5881f286bc28f64abe1f0"
    end
    on_intel do
      url "https://github.com/statico/ttmux/releases/download/v0.4.0/ttmux-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "be47290d36c329f2047d53147f5e8e451b14c6c8f60b88dcf897ee5d4129d1ad"
    end
  end

  def install
    bin.install "ttmux"
  end

  test do
    assert_match "ttmux #{version}", shell_output("#{bin}/ttmux -V")
    # --where needs no terminal, so it works in the sandbox.
    assert_match "ttmux.toml", shell_output("#{bin}/ttmux --where")
  end
end
